name: 'apkcombo-downloader'

author: "Ariel Tubul"
description: 'Download an apk from apkcombo'

branding:
  color: 'red'
  icon: 'smartphone'

inputs:
  package:
    description: 'Package name to download'
    required: true

  output-apk:
    description: 'Path to output apk file'
    required: true

  artifact-name:
    description: 'Name of artifact to upload'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'selenium/standalone-edge:dev'

  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Prepare apkmod
      run: pip install -r requirements.txt
      shell: pwsh

    - name: Download apk
      run: ./downloader.py --package ${{ inputs.package }} --path ${{ inputs.output-apk }}
      shell: pwsh

    - name: Upload downloaded apk
      if: inputs.artifact-name != ''
      uses: actions/upload-artifact@v3.1.2

      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.output-apk }}
