name: 'apkcombo-downloader'

author: 'Ariel Tubul'
description: 'Download an apk from apkcombo'

branding:
  color: 'red'
  icon: 'smartphone'

inputs:
  package:
    description: 'Package name to download'
    required: true

  output-apk:
    description: 'Path to output apk file (relative to `/github/workspace`)'
    required: true

  apk-language:
    description: 'Language of apk to download'
    required: false
    default: 'en'

  apk-device:
    description: 'Target device for the apk (phone / tablet / tv)'
    required: false
    default: 'default'

  apk-architecture:
    description: 'Target architecture for the apk (arm64-v8a / armeabi-v7a / x86 / x86_64)'
    required: false
    default: 'default'

  apk-dpi:
    description: 'Target apk dpi'
    required: false
    default: '480'

  apk-sdk:
    description: 'Target apk sdk'
    required: false
    default: 'default'

runs:
  using: 'docker'
  image: 'Dockerfile'

  args:
    - --package
    - ${{ inputs.package }}

    - --path
    - /github/workspace/${{ inputs.output-apk }}

    - --language
    - ${{ inputs.apk-language }}

    - --device
    - ${{ inputs.apk-device }}

    - --architecture
    - ${{ inputs.apk-architecture }}

    - --dpi
    - ${{ inputs.apk-dpi }}

    - --sdk
    - ${{ inputs.apk-sdk }}
